---
title: "NSF-BIO: Biological Sciences"
author: National Science Foundation
output: html_document
---

## Data and Materials Produced

Describe the types of data, physical samples or collections, software, curriculum materials, and other materials to be produced in the course of the project. (For collaborative proposals, the DMP must cover all the various data types being collected by each collaborator.)

Describe the data to be collected (actual observations) during your research including amount (if known). Name the type of data, the instrument or collection approach, and how the data will be sampled. If actual data are interpreted, note the interpretation. Describe any quality control measures. Also describe the final derivative products (datasets and software or computer code) and the analysis used including analytical software packages that are required for replication, etc. Describe data (both digital and analog) and physical materials (samples and collections) gathered or generated during the time of the award. Consider these questions:

•	What data will be generated in the research?
•	What data types will you be creating or capturing? (e.g. experimental measures, qualitative, raw, processed)
•	How will you capture or create the data? (This should cover content selection, instrumentation, technologies and approaches chosen, methods for naming, versioning, meeting user needs, etc, and should be sensitive to the location in which data capture is taking place)
•	If you will be using existing data, state that fact and include where you got it. What is the relationship between the data you are collecting and the existing data?

## Standards, Formats and Metadata

Describe the standards to be used for all the data types anticipated, including data or file format and metadata.

Describe the format of your data; think about what details (metadata) someone else would need to be able to use these files. Describe the structural standards that you will apply in making data and metadata available. For example, for most ecological data, documentation should be structured in Ecological Metadata Language (EML). An example of metadata could also be as simple as a "readme file" to explain variables, structure of the files, etc. Consider these questions:

•	Which file formats will you use for your data and why?
•	What form will the metadata describing/documenting your data take?
•	How will you create or capture these details?
•	Which metadata standards will you use and why have you chosen them? (e.g. accepted domain-local standards, widespread usage)
•	What contextual details (metadata) are needed to make the data you capture or collect meaningful?

## Roles and Responsibilities

Describe the roles and responsibilities of all parties with respect to the management of the data (including contingency plans for the departure of key personnel from the project).

Explain how the responsibilities regarding the management of your data will be delegated. This should include time allocations, project management of technical aspects, training requirements, and contributions of non-project staff - individuals should be named where possible. Remember that those responsible for long-term decisions about your data will likely be the custodians of the repository/archive you choose to store your data. While the costs associated with your research (and the results of your research) must be specified in the Budget Justification portion of the proposal, you may want to reiterate who will be responsible for funding the management of your data. Consider the following:

•	Outline the staff/organizational roles and responsibilities for implementing this data management plan.
•	Who will be responsible for data management and for monitoring the data management plan?
•	How will adherence to this data management plan be checked or demonstrated?
•	What process is in place for transferring responsibility for the data?
•	Who will have responsibility over time for decisions about the data once the original personnel are no longer available?

## Dissemination Methods

Describe the dissemination methods that will be used to make data and metadata available to others during the period of the award, and any modifications or additional technical information regarding data access after the grant ends.
Describe how and where you will make these data and metadata available to the community. Remember BIO is committed to timely and rapid data distribution; make sure you address how soon your data will be available. Indicate what data will be made available and preserved. Will data be accessible on a web page, by email request, via open-access repository, etc.? Consider these questions:

•	What data will be made available from the study and preserved for the long-term?
•	How and when will you make the data available? (Include resources needed to make the data available: equipment, systems, expertise, etc.)
•	What transformations will be necessary to prepare data for preservation / data sharing?
•	What metadata/ documentation will be submitted alongside the data or created on deposit/ transformation in order to make the data reusable?
•	What related information will be deposited?
•	What is the process for gaining access to the data?
•	How long will the original data collector/creator/principal investigator retain the right to use the data before opening it up to wider use?
•	Explain details of any embargo periods for political/commercial/patent or publisher reasons.

## Policies for Data Sharing and Public Access

Describe the PI’s policies for data sharing, public access and re-use, including re-distribution by others and the production of derivatives. Where appropriate, include provisions for protection of privacy, confidentiality, security, intellectual property rights and other rights.

Describe the policies under which these data will be made available. It is very important, the reason a DMP is required, that you specify how you will share your data with non-group members after the project is completed. If the data is of a sensitive nature—privacy or ecological endangerment concerns, for instance—and public access is inappropriate, address here the means by which granular control and access will be achieved (e.g. formal consent agreements, anonymized data, only available within a secure network, etc.). Consider these questions:

•	Will any permission restrictions need to be placed on the data?
•	Are there ethical and privacy issues? If so, how will these be resolved?
•	What have you done to comply with your obligations in your IRB Protocol?
•	Who will hold the intellectual property rights to the data and how might this affect data access?
•	What and who are the intended or foreseeable uses/users of the data?
•	Do you plan on publishing findings which rely on the data? If so, do your prospective publishers place any restrictions on other avenues of publication?

## Archiving, Storage and Preservation

Where relevant, describe plans for archiving data, samples, software, and other research products, and for on-going access to these products through their lifecycle of usefulness to research and education.

Consider which data (or research products) will be deposited for long-term access and where. (What physical and/or cyber resources and facilities (including third party resources) will be used to store and preserve the data after the grant ends?) 

 Describe your long-term strategy for storing, archiving and preserving the data you will generate or use. Consider the following:
 
•	What is the long-term strategy for maintaining, curating and archiving the data?
•	Which archive/repository/database have you identified as a place to deposit data?
•	What procedures does your intended long-term data storage facility have in place for preservation and backup?
•	How long will/should data be kept beyond the life of the project?
•	What data will be preserved for the long-term?
•	On what basis will data be selected for long-term preservation?
•	What metadata/documentation will be submitted alongside the data or created on deposit/transformation in order to make the data reusable?
•	What related information will be deposited?


